DROP TABLE IF EXISTS off_origin;

CREATE TABLE off_origin(
code VARCHAR(50),
url TEXT,
creator VARCHAR(50),
created_t BIGINT,
created_datetime TIMESTAMP WITH TIME ZONE,
last_modified_t BIGINT,
last_modified_datetime TIMESTAMP WITH TIME ZONE,
last_modified_by VARCHAR(50),
last_updated_t BIGINT,
last_updated_datetime TIMESTAMP WITH TIME ZONE,
product_name TEXT,
abbreviated_product_name VARCHAR(100),
generic_name TEXT,
quantity VARCHAR(50),
packaging VARCHAR(150),
packaging_tags VARCHAR(150),
packaging_fr VARCHAR(150),
packaging_text VARCHAR(150),
brands VARCHAR(150),
brands_tags VARCHAR(150),
categories TEXT,
categories_tags TEXT,
categories_fr TEXT,
origins VARCHAR(150),
origins_tags VARCHAR(150),
origins_fr VARCHAR(150),
manufacturing_places TEXT,
manufacturing_places_tags TEXT,
labels TEXT,
labels_tags TEXT,
labels_fr TEXT,
emb_codes VARCHAR(150),
emb_codes_tags VARCHAR(150),
first_packaging_code_geo VARCHAR(150),
cities VARCHAR(50),
cities_tags VARCHAR(150),
purchase_places TEXT,
stores TEXT,
countries TEXT,
countries_tags TEXT,
countries_fr TEXT,
ingredients_text TEXT,
ingredients_tags TEXT,
ingredients_analysis_tags TEXT,
allergens VARCHAR(150),
allergens_fr VARCHAR(50),
traces VARCHAR(200),
traces_tags VARCHAR(200),
traces_fr VARCHAR(200),
serving_size VARCHAR(150),
serving_quantity REAL,
no_nutrition_data VARCHAR(50),
additives_n INTEGER,
additives VARCHAR(50),
additives_tags VARCHAR(200),
additives_fr VARCHAR(200),
nutriscore_score INTEGER,
nutriscore_grade VARCHAR(50),
nova_group INTEGER,
pnns_groups_1 VARCHAR(100),
pnns_groups_2 VARCHAR(100),
food_groups VARCHAR(150),
food_groups_tags VARCHAR(200),
food_groups_fr VARCHAR(200),
states TEXT,
states_tags TEXT,
states_fr TEXT,
brand_owner VARCHAR(150),
environmental_score_score INTEGER,
environmental_score_grade VARCHAR(50),
nutrient_levels_tags VARCHAR(200),
product_quantity INTEGER,
owner VARCHAR(150),
data_quality_errors_tags TEXT,
unique_scans_n INTEGER,
popularity_tags TEXT,
completeness REAL,
last_image_t BIGINT,
last_image_datetime TIMESTAMP WITH TIME ZONE,
main_category VARCHAR(150),
main_category_fr VARCHAR(150),
image_url TEXT,
image_small_url TEXT,
image_ingredients_url TEXT,
image_ingredients_small_url TEXT,
image_nutrition_url TEXT,
image_nutrition_small_url TEXT,
energy_kj_100g DOUBLE PRECISION,
energy_kcal_100g DOUBLE PRECISION,
energy_100g DOUBLE PRECISION,
energy_from_fat_100g DOUBLE PRECISION,
fat_100g DOUBLE PRECISION,
saturated_fat_100g DOUBLE PRECISION,
butyric_acid_100g DOUBLE PRECISION,
caproic_acid_100g DOUBLE PRECISION,
caprylic_acid_100g DOUBLE PRECISION,
capric_acid_100g DOUBLE PRECISION,
lauric_acid_100g DOUBLE PRECISION,
myristic_acid_100g DOUBLE PRECISION,
palmitic_acid_100g DOUBLE PRECISION,
stearic_acid_100g DOUBLE PRECISION,
arachidic_acid_100g DOUBLE PRECISION,
behenic_acid_100g DOUBLE PRECISION,
lignoceric_acid_100g DOUBLE PRECISION,
cerotic_acid_100g DOUBLE PRECISION,
montanic_acid_100g DOUBLE PRECISION,
melissic_acid_100g DOUBLE PRECISION,
unsaturated_fat_100g DOUBLE PRECISION,
monounsaturated_fat_100g DOUBLE PRECISION,
omega_9_fat_100g DOUBLE PRECISION,
polyunsaturated_fat_100g DOUBLE PRECISION,
omega_3_fat_100g DOUBLE PRECISION,
omega_6_fat_100g DOUBLE PRECISION,
alpha_linolenic_acid_100g DOUBLE PRECISION,
eicosapentaenoic_acid_100g DOUBLE PRECISION,
docosahexaenoic_acid_100g DOUBLE PRECISION,
linoleic_acid_100g DOUBLE PRECISION,
arachidonic_acid_100g DOUBLE PRECISION,
gamma_linolenic_acid_100g DOUBLE PRECISION,
dihomo_gamma_linolenic_acid_100g DOUBLE PRECISION,
oleic_acid_100g DOUBLE PRECISION,
elaidic_acid_100g DOUBLE PRECISION,
gondoic_acid_100g DOUBLE PRECISION,
mead_acid_100g DOUBLE PRECISION,
erucic_acid_100g DOUBLE PRECISION,
nervonic_acid_100g DOUBLE PRECISION,
trans_fat_100g DOUBLE PRECISION,
cholesterol_100g DOUBLE PRECISION,
carbohydrates_100g DOUBLE PRECISION,
sugars_100g DOUBLE PRECISION,
added_sugars_100g DOUBLE PRECISION,
sucrose_100g DOUBLE PRECISION,
glucose_100g DOUBLE PRECISION,
fructose_100g DOUBLE PRECISION,
lactose_100g DOUBLE PRECISION,
maltose_100g DOUBLE PRECISION,
maltodextrins_100g DOUBLE PRECISION,
starch_100g DOUBLE PRECISION,
polyols_100g DOUBLE PRECISION,
erythritol_100g DOUBLE PRECISION,
fiber_100g DOUBLE PRECISION,
soluble_fiber_100g DOUBLE PRECISION,
insoluble_fiber_100g DOUBLE PRECISION,
proteins_100g DOUBLE PRECISION,
casein_100g DOUBLE PRECISION,
serum_proteins_100g DOUBLE PRECISION,
nucleotides_100g DOUBLE PRECISION,
salt_100g DOUBLE PRECISION,
added_salt_100g DOUBLE PRECISION,
sodium_100g DOUBLE PRECISION,
alcohol_100g DOUBLE PRECISION,
vitamin_a_100g DOUBLE PRECISION,
beta_carotene_100g DOUBLE PRECISION,
vitamin_d_100g DOUBLE PRECISION,
vitamin_e_100g DOUBLE PRECISION,
vitamin_k_100g DOUBLE PRECISION,
vitamin_c_100g DOUBLE PRECISION,
vitamin_b1_100g DOUBLE PRECISION,
vitamin_b2_100g DOUBLE PRECISION,
vitamin_pp_100g DOUBLE PRECISION,
vitamin_b6_100g DOUBLE PRECISION,
vitamin_b9_100g DOUBLE PRECISION,
folates_100g DOUBLE PRECISION,
vitamin_b12_100g DOUBLE PRECISION,
biotin_100g DOUBLE PRECISION,
pantothenic_acid_100g DOUBLE PRECISION,
silica_100g DOUBLE PRECISION,
bicarbonate_100g DOUBLE PRECISION,
potassium_100g DOUBLE PRECISION,
chloride_100g DOUBLE PRECISION,
calcium_100g DOUBLE PRECISION,
phosphorus_100g DOUBLE PRECISION,
iron_100g DOUBLE PRECISION,
magnesium_100g DOUBLE PRECISION,
zinc_100g DOUBLE PRECISION,
copper_100g DOUBLE PRECISION,
manganese_100g DOUBLE PRECISION,
fluoride_100g DOUBLE PRECISION,
selenium_100g DOUBLE PRECISION,
chromium_100g DOUBLE PRECISION,
molybdenum_100g DOUBLE PRECISION,
iodine_100g DOUBLE PRECISION,
caffeine_100g DOUBLE PRECISION,
taurine_100g DOUBLE PRECISION,
ph_100g DOUBLE PRECISION,
fruits_vegetables_nuts_100g DOUBLE PRECISION,
fruits_vegetables_nuts_dried_100g DOUBLE PRECISION,
fruits_vegetables_nuts_estimate_100g DOUBLE PRECISION,
fruits_vegetables_nuts_estimate_from_ingredients_100g DOUBLE PRECISION,
collagen_meat_protein_ratio_100g DOUBLE PRECISION,
cocoa_100g DOUBLE PRECISION,
chlorophyl_100g DOUBLE PRECISION,
carbon_footprint_100g DOUBLE PRECISION,
carbon_footprint_from_meat_or_fish_100g DOUBLE PRECISION,
nutrition_score_fr_100g INTEGER,
nutrition_score_uk_100g INTEGER,
glycemic_index_100g DOUBLE PRECISION,
water_hardness_100g DOUBLE PRECISION,
choline_100g DOUBLE PRECISION,
phylloquinone_100g DOUBLE PRECISION,
beta_glucan_100g DOUBLE PRECISION,
inositol_100g DOUBLE PRECISION,
carnitine_100g DOUBLE PRECISION,
sulphate_100g DOUBLE PRECISION,
nitrate_100g DOUBLE PRECISION,
acidity_100g DOUBLE PRECISION
);

\copy off_origin FROM 'ready.csv' WITH (FORMAT csv);